name: TestTestov
on: workflow_dispatch
jobs:
  GoTest:
    runs-on: windows-latest
    steps:
      - name: Get repo code
        uses: actions/checkout@v3
      - name: Restore
        run: dotnet restore PowerCollections/PowerCollections.csproj 
      - name: Build
        run: dotnet build PowerCollections/PowerCollections.csproj 
      - name: Test
        run: dotnet test PowerCollections.Tests/PowerCollections.Tests.csproj --no-restore
