name: TestNuget
on: workflow_dispatch
jobs:
  PackAndRelease:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Get repo code
        uses: actions/checkout@v3
      - name: nugetPack
        run: dotnet pack PowerCollections --configuration Release

      - name: GetVersion
        id: getxml
        uses: mavrosxristoforos/get-xml-info@1.0
        with:
          xml-file: 'PowerCollections/PowerCollections.csproj'
          xpath: '//VersionPrefix'
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'PowerCollections\bin\Release\*.nupkg'
          tag: ${{ steps.getxml.outputs.info }}
          token: ${{ secrets.API_KEY_GIT }}
        
